version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: cont-mysqlserver
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123123
      - MYSQL_DATABASE=bdnodeapp
    ports:
      - "3308:3306"
    networks:
      - net-mysqlserver
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  net-mysqlserver:

volumes:
  mysql-volume: